// Generated by CoffeeScript 1.6.1
(function() {

  describe("DiscussionThreadProfileView", function() {
    var checkBody, checkPostWithImages, makeThread, makeView, spyConvertMath;
    beforeEach(function() {
      setFixtures("<article class=\"discussion-thread\" id=\"thread_1\"></article>\n<script type='text/template' id='_profile_thread'>\n  <article class=\"discussion-article\" data-id=\"{{id}}\">\n    <div class=\"discussion-post local\">\n      <div class=\"post-body\">{{{abbreviatedBody}}}</div>\n    </div>\n  </article>\n</script>");
      this.threadData = {
        id: "1",
        body: "dummy body",
        discussion: new Discussion(),
        abuse_flaggers: [],
        votes: {
          up_count: "42"
        }
      };
      this.imageTag = '<img src="https://www.google.com.pk/images/srpr/logo11w.png">';
      return window.MathJax = {
        Hub: {
          Queue: function() {}
        }
      };
    });
    makeView = function(thread) {
      var view;
      view = new DiscussionThreadProfileView({
        el: $("article#thread_" + thread.id),
        model: thread
      });
      spyConvertMath(view);
      return view;
    };
    makeThread = function(threadData) {
      var thread;
      thread = new Thread(threadData);
      thread.discussion = new Discussion();
      return thread;
    };
    spyConvertMath = function(view) {
      return spyOn(view, "convertMath").andCallFake(function() {
        return this.model.set('markdownBody', this.model.get('body'));
      });
    };
    checkPostWithImages = function(numberOfImages, truncatedText, threadData, imageTag) {
      var expectedHtml, expectedText, i, testText, view, _i, _ref;
      expectedHtml = '<p>';
      threadData.body = '<p>';
      testText = '';
      expectedText = '';
      if (truncatedText) {
        testText = new Array(100).join('test ');
        expectedText = testText.substring(0, 139) + '…';
      } else {
        testText = 'Test body';
        expectedText = 'Test body';
        for (i = _i = 0, _ref = numberOfImages - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
          threadData.body = threadData.body + imageTag;
          if (i === 0) {
            expectedHtml = expectedHtml + imageTag;
          } else {
            expectedHtml = expectedHtml + '<em>image omitted</em>';
          }
        }
      }
      threadData.body = threadData.body + '<em>' + testText + '</em></p>';
      if (numberOfImages > 1) {
        expectedHtml = expectedHtml + '<em>' + expectedText + '</em></p><p><em>Some images in this post have been omitted</em></p>';
      } else {
        expectedHtml = expectedHtml + '<em>' + expectedText + '</em></p>';
      }
      view = makeView(makeThread(threadData));
      view.render();
      return expect(view.$el.find(".post-body").html()).toEqual(expectedHtml);
    };
    checkBody = function(truncated, view, threadData) {
      var expectedOutput, inputHtmlStripped, outputHtmlStripped;
      view.render();
      if (!truncated) {
        expect(view.model.get("body")).toEqual(view.model.get("abbreviatedBody"));
        return expect(view.$el.find(".post-body").html()).toEqual(threadData.body);
      } else {
        expect(view.model.get("body")).not.toEqual(view.model.get("abbreviatedBody"));
        expect(view.$el.find(".post-body").html()).not.toEqual(threadData.body);
        outputHtmlStripped = view.$el.find(".post-body").html().replace(/(<([^>]+)>)/ig, "");
        outputHtmlStripped = outputHtmlStripped.replace("Some images in this post have been omitted", "");
        outputHtmlStripped = outputHtmlStripped.replace("image omitted", "");
        inputHtmlStripped = threadData.body.replace(/(<([^>]+)>)/ig, "");
        expectedOutput = inputHtmlStripped.substring(0, 139) + '…';
        expect(outputHtmlStripped).toEqual(expectedOutput);
        return expect(view.$el.find(".post-body").html().indexOf("…")).toBeGreaterThan(0);
      }
    };
    return describe("Body markdown should be correct", function() {
      var numImages, truncatedText, _i, _len, _ref, _results;
      it("untruncated text without markdown body", function() {
        var view;
        this.threadData.body = "Test body";
        view = makeView(makeThread(this.threadData));
        return checkBody(false, view, this.threadData);
      });
      it("truncated text without markdown body", function() {
        var view;
        this.threadData.body = new Array(100).join("test ");
        view = makeView(makeThread(this.threadData));
        return checkBody(true, view, this.threadData);
      });
      it("untruncated text with markdown body", function() {
        var view;
        this.threadData.body = '<p>' + this.imageTag + '<em>Google top search engine</em></p>';
        view = makeView(makeThread(this.threadData));
        return checkBody(false, view, this.threadData);
      });
      it("truncated text with markdown body", function() {
        var testText, view;
        testText = new Array(100).join("test ");
        this.threadData.body = '<p>' + this.imageTag + this.imageTag + '<em>' + testText + '</em></p>';
        view = makeView(makeThread(this.threadData));
        return checkBody(true, view, this.threadData);
      });
      _ref = [1, 2, 10];
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        numImages = _ref[_i];
        _results.push((function() {
          var _j, _len1, _ref1, _results1;
          _ref1 = [true, false];
          _results1 = [];
          for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
            truncatedText = _ref1[_j];
            _results1.push(it("body with " + numImages + " images and " + (truncatedText ? "truncated" : "untruncated") + " text", function() {
              return checkPostWithImages(numImages, truncatedText, this.threadData, this.imageTag);
            }));
          }
          return _results1;
        })());
      }
      return _results;
    });
  });

}).call(this);
